# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoPaytabsObjectiveC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


	# Pods for sample-run
    pod 'BIObjCHelpers'
    pod 'IQKeyboardManager'
    pod 'AFNetworking'
    pod 'Mantle'
    pod 'Reachability'
    pod 'Lockbox'
    pod 'SBJson'
    pod 'PINCache'
    pod 'MBProgressHUD'
    pod 'ActionSheetPicker-3.0'
    # In case if you are using OCR version
    pod 'PayCardsRecognizer'

  # Pods for DemoPaytabsObjectiveC

  target 'DemoPaytabsObjectiveCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoPaytabsObjectiveCUITests' do
    # Pods for testing
  end

end
